version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout        # checkout source code to working directory

      - run: 
          name: Install Python deps in a venv
          command: |    # use pip to install dependencies
             python3 -m venv venv
             . venv/bin/activate
             pip install -r requirements.txt

      - run: 
           name: Run tests
           command: | 
             . venv/bin/activate
             mkdir test-reports
             nosetests test/math-test.py

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - run: coverage run src/*.py

      - run: coverage report
      
      - run: coveralls
